apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - bitnami-oci.yaml
  - gzac.yaml
  - kiss.yaml
  - maykin.yaml
  - woo.yaml
  - zac.yaml
  - nl-portal.yaml
