apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./brp-api
  - ./keycloak
  - ./kiss
  - ./nl-portal
  - ./objecten
  - ./objecttypen
  - ./openinwoner
  - ./openklant
  - ./opennotificaties
  - ./openproduct
  - ./openzaak
